backend:
  name: github
  repo: seuusuario/floridamaid-website # ⚠️ MUDE para seu usuário
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        fields:
          - {name: title, label: Title, widget: string}
          - {name: body, label: Content, widget: markdown}
